apiVersion: v1
kind: Service
metadata:
  labels:
    app: opentaxii
  name: opentaxii
spec:
  ports:
  - name: "9000"
    port: 80
    targetPort: 9000
  selector:
    app: opentaxii
  type: LoadBalancer
status:
  loadBalancer: {}
